version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "daily"
    labels:
      - "Skip Changelog"
      - "dependencies"
  - package-ecosystem: "pip"
    directory: /
    schedule:
      interval: "daily"
    labels:
      - "Skip Changelog"
      - "dependencies"
    ignore:
      # Upstream OTel dependencies are updated together during releases.
      - dependency-name: "opentelemetry-*"
