version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "Skip Changelog"
      - "dependencies"
    allowed_updates:
      - match:
          update_type: "security"
